[package]
name = "lalrpop-lambda"
description = "A Î»-calculus grammar writting with LALRPOP."
repository = "https://github.com/nixpulvis/lalrpop-lambda"
version = "0.4.1"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]
license = "MIT"
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
lalrpop-util = "0.17.0"
regex = "0.2.0"
# TODO: Make feature.
wasm-bindgen = "0.2"

[build-dependencies]
lalrpop = "0.17.0"

[dev-dependencies]
pretty_assertions = "0.6"
criterion = "0.2"

[[bench]]
name = "numerals"
harness = false
